/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package javaapplication12;

import javax.swing.table.DefaultTableModel;

/**
 *
 * @author manue
 */
public class NewJFrame extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    
    DefaultTableModel m;
    int n;
   // int j=1;
    String data[][];
    //String columnNames []={"nombre"+(j+3),"edad"};
     String columnNames[] ;
     String nom[]= new String [n];
   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jText_Entrada = new javax.swing.JTextField();
        Btn_Datos = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        Btn_Ordenar_ = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jText_Entrada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jText_EntradaActionPerformed(evt);
            }
        });

        Btn_Datos.setText("ACPETAR");
        Btn_Datos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_DatosActionPerformed(evt);
            }
        });

        jLabel1.setText("Ingrese Numero de Datos a Ingresar: ");

        Btn_Ordenar_.setText("ORDENAR");
        Btn_Ordenar_.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_Ordenar_ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(191, 191, 191)
                        .addComponent(Btn_Ordenar_))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 461, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jText_Entrada, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(Btn_Datos)))))
                .addContainerGap(40, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jText_Entrada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Btn_Datos))
                .addGap(25, 25, 25)
                .addComponent(Btn_Ordenar_)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(174, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
 public NewJFrame() {
        initComponents();
        
        m=new DefaultTableModel(data, columnNames);
        jTable1.setModel(m);
        m.setRowCount(3);
      
    }
    private void Btn_DatosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_DatosActionPerformed
        n=Integer.parseInt(jText_Entrada.getText());
  
    columnNames = new String [n];
        for(int i=0;i<columnNames.length;i++)
        {
           columnNames[i]="num "+(i+1);
                
        }
         m.setColumnCount(n);
         m.setColumnIdentifiers(columnNames);
    }//GEN-LAST:event_Btn_DatosActionPerformed

    private void jText_EntradaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jText_EntradaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jText_EntradaActionPerformed

    private void Btn_Ordenar_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_Ordenar_ActionPerformed
     
        
        
        /* for(int i=0;i<data.length;i++)
       {
           for(int j=0; i<data.length; i++)
           {
               System.out.println("fila"+data[i]);
                System.out.println("colum"+data[j]);
           }
        
       }*/
     // int i=0;
    //  String ho [] =new String[n];
    
      for (int i=0;i<nom.length;i++)
      {
       
              
         
          nom[i]=jText_Entrada.getText();
       m.addRow(nom);
     // m.addRow(ho);
        
      }
    
// int i=0;
      // data[0][i]=Integer.parseInt(jText_Entrada.getText());
        System.out.println("ddd"+nom);
    }//GEN-LAST:event_Btn_Ordenar_ActionPerformed

 
 public void ordednar()
 {
     
 }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Btn_Datos;
    private javax.swing.JButton Btn_Ordenar_;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jText_Entrada;
    // End of variables declaration//GEN-END:variables
}
